console.log("Prepararse");
console.log("Revisar la lista");
console.log("Revisar tener la vestimenta adecuada");
console.log("Planificar la ruta");
console.log("Salir de casa");
console.log("Dirigirme al supermercado");
console.log("Llegar al supermercado y entrar");
console.log("Reunir los productos que deseo comprar");
console.log("Pagar los productos");
console.log("Volver a mi casa");
