console.log("1- Preparar los ingredientes");
console.log("2- Precalentar el horno a º180");
console.log("3- Mezclar los ingredientes secos");
console.log("4- Mezclar los ingredientes humedos");
console.log("5- Combinar los ingredientes");
console.log("6- Preparar el molde previamente enharinado");
console.log("7- Verter la mezcla");
console.log("8- Hornear");
console.log("9- Dejar enfriar");
console.log("10- Decorar y disfrutar");